### ISSUE TITLE
P.13 図1-13 Bisonによって生成されたパーサコードのファイル名がparse.yになっている

### ISSUE THREAD

**Issue by muramasa64** [ohmsha/ruby-under-a-microscope-ja#1]
P.13 図1-13 Bisonによって生成されたパーサコードのファイル名がparse.yになっています。
これは、parese.cのtypoではないでしょうか。

**Comment by snoozer05** [comment]
おお...さっそくありがとうございます！本当ですね...
次版を出す際には修正するようにいたします。ご指摘ありがとうございます！

**Comment by muramasa64** [comment]
よろしくお願いします！

**Comment by hisashim** [comment]
第2刷で修正させていただきます。ありがとうございます。
