### ISSUE TITLE
p. 157 角括弧じゃないのではないか

### ISSUE THREAD

**Issue by kou** [ohmsha/ruby-under-a-microscope-ja#10]
「<」のことを「角括弧」と指している気がするが、角括弧ではないのではないか。Wikipediaの角括弧の説明  http://ja.wikipedia.org/wiki/%E6%8B%AC%E5%BC%A7#.E8.A7.92.E6.8B.AC.E5.BC.A7.EF.BC.BB.EF.BC.BD だと「[」のことみたいです。

個人的には「X括弧」と書かれるより「<...>」のように実際の記号で書いてもらったほうがわかりやすいです。

**Comment by snoozer05** [comment]
oo... 正しくは 山形括弧 ですね。。
ですが、山形括弧と書かれてもピンとこない読者も多そうですし、ご提案の通り <...> で直したいと思います。ありがとうございます。

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。
