### ISSUE TITLE
p. 260 「print文による出力」ではなく「p文による出力」

### ISSUE THREAD

**Issue by kou** [ohmsha/ruby-under-a-microscope-ja#12]
さらに細かいことを言うと「文」ではなく「式」です。

**Comment by snoozer05** [comment]
原文を確認すると `the print statements` となっているので、それに引きずられてしまったのですねえ...失礼しました。より自然に読めるように、pメソッドと修正しようと思います。

**Comment by kou** [comment]
であれば「出力内容を」くらいでいいかもしれません！

**Comment by snoozer05** [comment]
おお、そうですね...!! やってきます

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。
