### ISSUE TITLE
p.21 「第 1(primary)の文法規則」

### ISSUE THREAD

**Issue by nobu** [ohmsha/ruby-under-a-microscope-ja#3]
順序付けられているわけではないので、「第 1」という訳語は不適切だと思います。
ここは、次のページのようにコードとしてprimaryそのままのほうがよいのではないでしょうか。
また、次のページでもprimaryだけがmonospaceになっていませんが、他の規則名に合わせるべきだと思います。

**Comment by hisashim** [comment]
ご指摘ありがとうございます。次のような感じでしょうか。

p. 21:

> Rubyの解析が第1（primary）の文法規則へと到達すると
> Rubyの解析が<code>primary</code>の文法規則へと到達すると

p.22:

> 続く別のprimaryの値に一致していることがわかる。
> 続く別の<code>primary</code>の値に一致していることがわかる。

@snoozer05 @kakutani いかがでしょう。指示いただければ適宜対応します。

**Comment by nobu** [comment]
遅くなってすいません。
どちらもそれでよいと思います。

**Comment by snoozer05** [comment]
@hisashim ありがとうございます。対応をお願いできますでしょうか ><

**Comment by hisashim** [comment]
@snoozer05 承知しました。確認しながら修正しておきます。
@nobu どうもありがとうございます。編集が至らず恐縮です。
ほかにも何かお気づきでしたら、遠慮なくご指摘くださるとありがたいです。

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。
