### ISSUE TITLE
P.76  下から二行目「puts self呼び出しのために...」

### ISSUE THREAD

**Issue by pocket7878** [ohmsha/ruby-under-a-microscope-ja#4]
こちらなのですが、`puts self`ではなく`puts str`ではないでしょうか？

**Comment by snoozer05** [comment]
おお、本当ですね... `puts str` が正しいです！
次版を出す際に修正するようにいたします。ご指摘ありがとうございます！

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。
