### ISSUE TITLE
P.121 L.4 「図5-5に示すように」

### ISSUE THREAD

**Issue by yui-knk** [ohmsha/ruby-under-a-microscope-ja#5]
`図5-5に示すように...`は`リスト5-5に示すように...`が正ではないでしょうか？

**Comment by snoozer05** [comment]
確認致しました。確かに、`リスト5-5に示すように` が正しいです >< 修正いたします。
ご指摘ありがとうございます！

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。
