### ISSUE TITLE
p. 140, 「ハッシュテーブル、」が不要

### ISSUE THREAD

**Issue by hisashim** [ohmsha/ruby-under-a-microscope-ja#6]
p.140

最下行から2行目の「ハッシュテーブル、」は不要。

変更前: 

> Rubyはクラスごとの情報の大半を、属性名テーブル、メソッドテーブル、
> クラスインスタンス変数テーブル、ハッシュテーブル、定数テーブルという、
> 4つのハッシュテーブルを使って保存する。

変更後:

> Rubyはクラスごとの情報の大半を、属性名テーブル、メソッドテーブル、
> クラスインスタンス変数テーブル、定数テーブルという、
> 4つのハッシュテーブルを使って保存する。

// 読者のS.D.さんからのご指摘。

**Comment by hisashim** [comment]
@snoozer05 confirmいただけたら直します。

**Comment by snoozer05** [comment]
@hisashim おねがいいたします！

**Comment by hisashim** [comment]
手元で直しました。引き取ります。

**Comment by hisashim** [comment]
第2刷で修正しました。
