### ISSUE TITLE
p. 63 「CFPポインタ」の「ポインタ」が余計

### ISSUE THREAD

**Issue by kou** [ohmsha/ruby-under-a-microscope-ja#7]
CFPはcontrol frame pointerでポインタを含んでいるから。

**Comment by snoozer05** [comment]
ありがとうございます。

原文が「CFP pointer」となっていて、それを素直に訳した結果このようになってしまっていたのでした。他にもEPなども「EP pointer」となっていて最初は「EPポインタ」としていたのですが、そちらはレビューにて「EP」としていたのですが、CFPの方はそのまま抜けてしまっていました...

修正するようにします。

**Comment by hisashim** [comment]
第2刷で修正しました。ありがとうございます。

**Comment by hisashim** [comment]
補足: 修正箇所はpp. 63, 66-67, 98です。
